// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FlexibleText accepts either a plain string or a multimodal array of parts
 * (as returned for messages that carry images/blocks).
 */
export type FlexibleText = string;

/**
 * HubNode is one node of the atlas-hub tree (guild / category / channel / post).
 */
export interface HubNode {
    "kind": string;
    "name": string;
    "session_id"?: string;
    "profile"?: string;
    "chat_type"?: string;
    "last_active"?: number;
    "message_count"?: number;
    "pinned"?: boolean;
    "children"?: HubNode[] | null;
}

/**
 * HubTree is the /tree payload from atlas-hub.
 */
export interface HubTree {
    "generated_at": number;
    "sections": HubNode[] | null;
    "errors": string[] | null;
}

export interface Message {
    "id": number;
    "role": string;
    "content": FlexibleText;
    "tool_name": string;
    "tool_calls": ToolCall[] | null;
    "reasoning": FlexibleText;
    "timestamp": number;
}

export interface Session {
    "id": string;
    "source": string;
    "title": string;
    "preview": string;
    "message_count": number;
    "last_active": number;
    "pinned": boolean;
    "hidden": boolean;
    "archived": boolean;
}

export interface ToolCall {
    "function": {"name": string, "arguments": string};
}
