// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataService is the app's single bridge to head services. ALL HTTP happens
 * here, on the Go side: no CORS in the webview, no bearer keys in the
 * frontend, and the exact same client code the TUI uses (atlas/internal/hermes).
 * This is also the seam where a head-side daemon slots in later without the
 * frontend noticing.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hermes$0 from "../internal/hermes/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetMessages reads one conversation's transcript.
 */
export function GetMessages(profile: string, sessionID: string, limit: number): $CancellablePromise<hermes$0.Message[] | null> {
    return $Call.ByID(37539999, profile, sessionID, limit);
}

/**
 * GetSessions is the flat fallback list when the hub is unavailable.
 */
export function GetSessions(limit: number): $CancellablePromise<hermes$0.Session[] | null> {
    return $Call.ByID(3233894390, limit);
}

/**
 * GetTree fetches the full workstream tree from the hub (all profiles).
 */
export function GetTree(): $CancellablePromise<hermes$0.HubTree | null> {
    return $Call.ByID(3482604795);
}

/**
 * InitialSession is read by the frontend during boot.
 */
export function InitialSession(): $CancellablePromise<string> {
    return $Call.ByID(1803504045);
}

/**
 * SendMessage starts one agent turn asynchronously. Deltas and lifecycle
 * updates stream back on the "atlas:turn" event as they arrive; the call
 * returns immediately.
 */
export function SendMessage(profile: string, sessionID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(439076974, profile, sessionID, text);
}

/**
 * SetInitialSession wires the --open flag: boot straight into one session.
 */
export function SetInitialSession(id: string): $CancellablePromise<void> {
    return $Call.ByID(3296726963, id);
}

export function Status(): $CancellablePromise<$models.Status> {
    return $Call.ByID(1095129455);
}

/**
 * StopTurn asks the API server to interrupt the session's in-flight run.
 * If the run id has not arrived yet, it waits briefly for it; failing that
 * it detaches the local stream (the run may finish server-side).
 */
export function StopTurn(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3606818042, sessionID);
}
