// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataService is the app's single bridge to head services. ALL HTTP happens
 * here, on the Go side: no CORS in the webview, no bearer keys in the
 * frontend, and the exact same client code the TUI uses (atlas/internal/hermes).
 * This is also the seam where a head-side daemon slots in later without the
 * frontend noticing.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as hermes$0 from "../internal/hermes/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetMessages reads one conversation's transcript.
 */
export function GetMessages(profile: string, sessionID: string, limit: number): $CancellablePromise<hermes$0.Message[] | null> {
    return $Call.ByID(37539999, profile, sessionID, limit);
}

/**
 * GetSessions is the flat fallback list when the hub is unavailable.
 */
export function GetSessions(limit: number): $CancellablePromise<hermes$0.Session[] | null> {
    return $Call.ByID(3233894390, limit);
}

/**
 * GetTree fetches the full workstream tree from the hub (all profiles).
 */
export function GetTree(): $CancellablePromise<hermes$0.HubTree | null> {
    return $Call.ByID(3482604795);
}

/**
 * SendMessage runs one full agent turn (blocking until the run completes).
 * Streaming deltas come later; M1 keeps the turn synchronous.
 */
export function SendMessage(profile: string, sessionID: string, text: string): $CancellablePromise<void> {
    return $Call.ByID(439076974, profile, sessionID, text);
}

export function Status(): $CancellablePromise<$models.Status> {
    return $Call.ByID(1095129455);
}
