// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Status reports which upstreams are configured, for the status bar.
 */
export interface Status {
    "api": boolean;
    "hub": boolean;
    "api_url": string;
    "hub_url": string;
}
